//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp_V2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneKlientow
    {
        public DaneKlientow()
        {
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.Konto = new HashSet<Konto>();
        }
    
        public string Nr_konta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Pesel { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Miasto { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<Konto> Konto { get; set; }
    }
}
