//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp_V2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konto
    {
        public Konto()
        {
            this.Przelew = new HashSet<Przelew>();
        }
    
        public string UserId { get; set; }
        public int KontoId { get; set; }
        public decimal Saldo { get; set; }
        public string Nazwa { get; set; }
        public string Status { get; set; }
    
        public virtual DaneKlientow DaneKlientow { get; set; }
        public virtual ICollection<Przelew> Przelew { get; set; }
    }
}
