//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp_V2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredyty
    {
        public int KredytID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Rata { get; set; }
        public Nullable<int> Okres { get; set; }
        public Nullable<System.DateTime> DataZawarcia { get; set; }
        public Nullable<System.DateTime> DataZamkniecia { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> oprocentowanie { get; set; }
        public Nullable<int> zostalorat { get; set; }
    }
}
