//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp_V2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przelew
    {
        public string UserId { get; set; }
        public string KontoId { get; set; }
        public string Typ { get; set; }
        public string Tytul { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Miasto { get; set; }
        public decimal Kwota { get; set; }
        public int Przelew_ID { get; set; }
        public int NumerKontaOdbiorcy { get; set; }
        public int NumerKontaNadawcy { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> SaldoPo { get; set; }
        public string KontoIDOdbiorcy { get; set; }
        public Nullable<decimal> SaldoPoOdbiorcy { get; set; }
    
        public virtual Konto Konto { get; set; }
    }
}
